# These are supported funding model platforms

github: [therealdreg]
patreon: dreg
custom: ["https://www.paypal.me/therealdreg", "https://www.cointracker.io/wallet/bitcoin?address=34or74iWCG9wHqonxBjxgPKargcTbAdJvi"]

